name: Deploy Examples
on:
  push:
    branches:
      - main
      - nm-test

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  deploy:
    concurrency: main
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: xmtpeng
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Push
        id: push
        run: |
          export DOCKER_IMAGE_TAG=latest
          IMAGE_TO_DEPLOY=xmtp/bot-examples@$(dev/docker/push-examples)
          echo Successfully pushed $IMAGE_TO_DEPLOY
          echo "docker_image=${IMAGE_TO_DEPLOY}" >> $GITHUB_OUTPUT

      - name: Deploy (dev)
        uses: xmtp-labs/terraform-deployer@v1
        with:
          terraform-token: ${{ secrets.TERRAFORM_TOKEN }}
          terraform-org: xmtp
          terraform-workspace: dev
          variable-name: bot_examples_docker_image
          variable-value: ${{ steps.push.outputs.docker_image }}
          variable-value-required-prefix: "xmtp/bot-examples@sha256:"

    #   - name: Deploy (production)
    #     uses: xmtp-labs/terraform-deployer@v1
    #     with:
    #       terraform-token: ${{ secrets.TERRAFORM_TOKEN }}
    #       terraform-org: xmtp
    #       terraform-workspace: production
    #       variable-name: bot_examples_image
    #       variable-value: ${{ steps.push.outputs.docker_image }}
    #       variable-value-required-prefix: "xmtp/bot-examples@sha256:"
