name: Test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"
      - name: Install Yarn v4
        run: |
          corepack enable
          corepack prepare yarn@4.0.0-rc.51 --activate
      - run: yarn
      - run: yarn build
      - run: yarn workspace @xmtp/bot-kit-pro run up
      - run: yarn test
